// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3iR-vmpLOGlkHcGtpWb0ki7rDbdgaw8',
    appId: '1:276565192559:web:ca9a70345c9e27cf9d029a',
    messagingSenderId: '276565192559',
    projectId: 'feature-autentication',
    authDomain: 'feature-autentication.firebaseapp.com',
    storageBucket: 'feature-autentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDChjrd6h1S6yiIbdB2xVdB3YifwFxHuKo',
    appId: '1:276565192559:android:4a1434482968a5129d029a',
    messagingSenderId: '276565192559',
    projectId: 'feature-autentication',
    storageBucket: 'feature-autentication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFg3aBqYbyWWX1U7BBOK0Ub4eU9Sno5bY',
    appId: '1:276565192559:ios:1dd37fafab9785c89d029a',
    messagingSenderId: '276565192559',
    projectId: 'feature-autentication',
    storageBucket: 'feature-autentication.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.featureAutentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFg3aBqYbyWWX1U7BBOK0Ub4eU9Sno5bY',
    appId: '1:276565192559:ios:1dd37fafab9785c89d029a',
    messagingSenderId: '276565192559',
    projectId: 'feature-autentication',
    storageBucket: 'feature-autentication.firebasestorage.app',
    iosBundleId: 'com.santos.valdomiro.featureAutentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa3iR-vmpLOGlkHcGtpWb0ki7rDbdgaw8',
    appId: '1:276565192559:web:b1d6d3026dc44bd29d029a',
    messagingSenderId: '276565192559',
    projectId: 'feature-autentication',
    authDomain: 'feature-autentication.firebaseapp.com',
    storageBucket: 'feature-autentication.firebasestorage.app',
  );
}
